import { describe, expect, it } from "vitest";
import { GATE_ERROR_CODES, WORKFLOW_ERROR_CODES } from "./errors.js";

describe("GATE_ERROR_CODES", () => {
  it("exposes the MVP gate error codes", () => {
    expect(GATE_ERROR_CODES).toEqual({
      GATE_TIMEOUT: "GATE_TIMEOUT",
      GATE_EXCEPTION: "GATE_EXCEPTION",
      GATE_INVALID_OUTPUT: "GATE_INVALID_OUTPUT",
      GATE_SANDBOX_CRASH: "GATE_SANDBOX_CRASH",
    });
  });

  it("is frozen at runtime", () => {
    expect(Object.isFrozen(GATE_ERROR_CODES)).toBe(true);
  });
});

describe("WORKFLOW_ERROR_CODES", () => {
  it("exposes the MVP workflow error codes (round 3: +T3 cancellation/forbidden/invalid_input, +T5 composite codes)", () => {
    expect(WORKFLOW_ERROR_CODES).toEqual({
      WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
      WORKFLOW_RUN_NOT_FOUND: "WORKFLOW_RUN_NOT_FOUND",
      WORKFLOW_DEPENDENCY_UNMET: "WORKFLOW_DEPENDENCY_UNMET",
      WORKFLOW_STEP_NOT_FOUND: "WORKFLOW_STEP_NOT_FOUND",
      WORKFLOW_INVALID_ARTIFACT: "WORKFLOW_INVALID_ARTIFACT",
      WORKFLOW_GATE_FAILED: "WORKFLOW_GATE_FAILED",
      WORKFLOW_ALREADY_COMPLETED: "WORKFLOW_ALREADY_COMPLETED",
      AGENTS_STALE: "AGENTS_STALE",
      MISSING_TOOLS: "MISSING_TOOLS",
      GIT_PROVIDER_MISCONFIG: "GIT_PROVIDER_MISCONFIG",
      WORKFLOW_VALIDATION: "WORKFLOW_VALIDATION",
      WORKFLOW_NAME_MISMATCH: "WORKFLOW_NAME_MISMATCH",
      GATE_SOURCE_NOT_FOUND: "GATE_SOURCE_NOT_FOUND",
      GIT_PROVIDER_ERROR: "GIT_PROVIDER_ERROR",
      WORKFLOW_FILE_INVALID_PATH: "WORKFLOW_FILE_INVALID_PATH",
      WORKFLOW_FILE_NOT_FOUND: "WORKFLOW_FILE_NOT_FOUND",
      WORKFLOW_FILE_EMPTY_CHANGES: "WORKFLOW_FILE_EMPTY_CHANGES",
      AGENT_NOT_REGISTERED: "AGENT_NOT_REGISTERED",
      AGENT_GIT_FILE_MISSING: "AGENT_GIT_FILE_MISSING",
      // T3 — assignments / cancellation / forbidden
      WORKFLOW_FORBIDDEN: "WORKFLOW_FORBIDDEN",
      WORKFLOW_INVALID_INPUT: "WORKFLOW_INVALID_INPUT",
      WORKFLOW_RUN_ALREADY_CANCELLED: "WORKFLOW_RUN_ALREADY_CANCELLED",
      WORKFLOW_RUN_CANCELLED: "WORKFLOW_RUN_CANCELLED",
      WORKFLOW_RUN_NOT_ACTIVE: "WORKFLOW_RUN_NOT_ACTIVE",
      WORKFLOW_RUN_NOT_CANCELLED: "WORKFLOW_RUN_NOT_CANCELLED",
      // T5 — composite workflows
      WORKFLOW_COMPOSITE_CYCLE: "WORKFLOW_COMPOSITE_CYCLE",
      WORKFLOW_COMPOSITE_DEPTH_EXCEEDED: "WORKFLOW_COMPOSITE_DEPTH_EXCEEDED",
      WORKFLOW_COMPOSITE_FANOUT_EXCEEDED: "WORKFLOW_COMPOSITE_FANOUT_EXCEEDED",
      WORKFLOW_COMPOSITE_USES_NOT_FOUND: "WORKFLOW_COMPOSITE_USES_NOT_FOUND",
      WORKFLOW_USES_INVALID: "WORKFLOW_USES_INVALID",
    });
  });

  it("includes GATE_SOURCE_NOT_FOUND", () => {
    expect(WORKFLOW_ERROR_CODES.GATE_SOURCE_NOT_FOUND).toBe("GATE_SOURCE_NOT_FOUND");
  });

  it("is frozen at runtime", () => {
    expect(Object.isFrozen(WORKFLOW_ERROR_CODES)).toBe(true);
  });

  it("includes WORKFLOW_RUN_NOT_FOUND", () => {
    expect(WORKFLOW_ERROR_CODES.WORKFLOW_RUN_NOT_FOUND).toBe("WORKFLOW_RUN_NOT_FOUND");
  });

  it("includes WORKFLOW_GATE_FAILED", () => {
    expect(WORKFLOW_ERROR_CODES.WORKFLOW_GATE_FAILED).toBe("WORKFLOW_GATE_FAILED");
  });
});
