/**
 * Per-instance LLM configuration.
 *
 * Lets the admin set an LLM provider + API key from the in-app onboarding
 * wizard (or admin settings) instead of editing `.env`. Required for the
 * standalone-mode UX where the colleague should never have to touch a shell.
 *
 * Storage: encrypted JSON at `${MNM_HOME}/instances/${MNM_INSTANCE_ID}/llm-config.json`,
 * encrypted with AES-256-GCM keyed off `MNM_SECRETS_KEY` (the same secret the
 * `local_encrypted` secrets provider uses, auto-generated by the Docker
 * entrypoint in standalone mode). The file is mode 0600.
 *
 * Resolution order in callers (`getActiveLlmKey`):
 *   1. DB-stored (this module) — set via PUT /instance-config/llm
 *   2. process.env.ANTHROPIC_API_KEY — for users on classic .env workflow
 *   3. null — graceful "no LLM" fallbacks kick in
 */

import { createCipheriv, createDecipheriv, randomBytes, createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync, chmodSync } from "node:fs";
import path from "node:path";
import { resolveMnMConfigPath } from "../paths.js";

export type LlmProvider = "anthropic" | "openai";

export interface InstanceLlmConfigPublic {
  provider: LlmProvider | null;
  hasKey: boolean;
  /** Last 4 chars of the stored key — for display only ("sk-…abcd"). */
  keyHint: string | null;
  updatedAt: string | null;
  /** True when an `ANTHROPIC_API_KEY` env var is providing the key instead of stored config. */
  fromEnv: boolean;
}

interface StoredConfig {
  scheme: "local_encrypted_v1";
  provider: LlmProvider;
  iv: string;
  tag: string;
  ciphertext: string;
  keyHint: string;
  updatedAt: string;
}

function resolveConfigFilePath(): string {
  // Sibling of the same `${MNM_HOME}/instances/<id>/.env` & `config.json`
  // so a single mount covers both runtime config + auto-generated secrets.
  const dir = path.dirname(resolveMnMConfigPath());
  return path.resolve(dir, "llm-config.json");
}

function decodeKey(raw: string): Buffer | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (/^[A-Fa-f0-9]{64}$/.test(trimmed)) return Buffer.from(trimmed, "hex");
  try {
    const decoded = Buffer.from(trimmed, "base64");
    if (decoded.length === 32) return decoded;
  } catch {
    // ignored
  }
  if (Buffer.byteLength(trimmed, "utf8") === 32) {
    return Buffer.from(trimmed, "utf8");
  }
  return null;
}

function loadMasterKey(): Buffer | null {
  const fromEnv = process.env.MNM_SECRETS_KEY ?? process.env.MNM_SECRETS_MASTER_KEY;
  if (fromEnv) {
    const decoded = decodeKey(fromEnv);
    if (decoded) return decoded;
  }
  // Derive a stable key from a known instance fingerprint when no master is
  // set. This keeps the API usable in plain `bun run dev` without forcing
  // env setup; the encrypted blob is then only protected by filesystem
  // permissions, which is acceptable for local-dev convenience.
  const fingerprint = process.env.MNM_INSTANCE_ID ?? "default";
  return createHash("sha256").update(`mnm-llm-config:${fingerprint}`).digest();
}

function encrypt(masterKey: Buffer, value: string): { iv: string; tag: string; ciphertext: string } {
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", masterKey, iv);
  const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return {
    iv: iv.toString("base64"),
    tag: tag.toString("base64"),
    ciphertext: ciphertext.toString("base64"),
  };
}

function decrypt(masterKey: Buffer, blob: { iv: string; tag: string; ciphertext: string }): string {
  const iv = Buffer.from(blob.iv, "base64");
  const tag = Buffer.from(blob.tag, "base64");
  const ciphertext = Buffer.from(blob.ciphertext, "base64");
  const decipher = createDecipheriv("aes-256-gcm", masterKey, iv);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
}

function readStored(): StoredConfig | null {
  const file = resolveConfigFilePath();
  if (!existsSync(file)) return null;
  try {
    const raw = readFileSync(file, "utf8");
    const parsed = JSON.parse(raw);
    if (parsed?.scheme !== "local_encrypted_v1") return null;
    return parsed as StoredConfig;
  } catch {
    return null;
  }
}

function writeStored(stored: StoredConfig): void {
  const file = resolveConfigFilePath();
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(stored, null, 2), { mode: 0o600 });
  try {
    chmodSync(file, 0o600);
  } catch {
    // best effort
  }
}

function maskKey(value: string): string {
  if (value.length <= 4) return "****";
  return `${"*".repeat(Math.max(4, value.length - 4))}${value.slice(-4)}`;
}

/**
 * Returns the active LLM API key + provider, preferring the encrypted store
 * over `process.env`. Returns `null` when nothing is configured.
 */
export function getActiveLlmKey(): { provider: LlmProvider; apiKey: string } | null {
  const stored = readStored();
  if (stored) {
    const masterKey = loadMasterKey();
    if (masterKey) {
      try {
        const apiKey = decrypt(masterKey, stored);
        if (apiKey) return { provider: stored.provider, apiKey };
      } catch {
        // fall through to env
      }
    }
  }
  const envKey = process.env.ANTHROPIC_API_KEY?.trim();
  if (envKey) return { provider: "anthropic", apiKey: envKey };
  const openAiEnv = process.env.OPENAI_API_KEY?.trim();
  if (openAiEnv) return { provider: "openai", apiKey: openAiEnv };
  return null;
}

/** Public-safe view of the current config — no secrets. */
export function getInstanceLlmConfigPublic(): InstanceLlmConfigPublic {
  const stored = readStored();
  if (stored) {
    return {
      provider: stored.provider,
      hasKey: true,
      keyHint: stored.keyHint,
      updatedAt: stored.updatedAt,
      fromEnv: false,
    };
  }
  const envKey = process.env.ANTHROPIC_API_KEY?.trim();
  if (envKey) {
    return {
      provider: "anthropic",
      hasKey: true,
      keyHint: maskKey(envKey),
      updatedAt: null,
      fromEnv: true,
    };
  }
  const openAiEnv = process.env.OPENAI_API_KEY?.trim();
  if (openAiEnv) {
    return {
      provider: "openai",
      hasKey: true,
      keyHint: maskKey(openAiEnv),
      updatedAt: null,
      fromEnv: true,
    };
  }
  return { provider: null, hasKey: false, keyHint: null, updatedAt: null, fromEnv: false };
}

export function setInstanceLlmConfig(input: { provider: LlmProvider; apiKey: string }): InstanceLlmConfigPublic {
  const trimmed = input.apiKey.trim();
  if (!trimmed) {
    throw new Error("apiKey must be a non-empty string");
  }
  const masterKey = loadMasterKey();
  if (!masterKey) {
    throw new Error("Cannot encrypt LLM config: master key unavailable");
  }
  const { iv, tag, ciphertext } = encrypt(masterKey, trimmed);
  const stored: StoredConfig = {
    scheme: "local_encrypted_v1",
    provider: input.provider,
    iv,
    tag,
    ciphertext,
    keyHint: maskKey(trimmed),
    updatedAt: new Date().toISOString(),
  };
  writeStored(stored);
  return {
    provider: stored.provider,
    hasKey: true,
    keyHint: stored.keyHint,
    updatedAt: stored.updatedAt,
    fromEnv: false,
  };
}

export function clearInstanceLlmConfig(): void {
  const file = resolveConfigFilePath();
  if (existsSync(file)) {
    try {
      unlinkSync(file);
    } catch {
      // best effort
    }
  }
}
